#!/bin/bash
# dwb: Control y
tmpdir=~/tmp
tmpfile=youtube.mp4
mkdir -p $tmpdir
rm -rf $tmpdir/$tmpfile
youtube-dl --output $tmpdir/$tmpfile $DWB_URI > $tmpdir/youtube-dl.log 2>&1
mplayer $tmpdir/$tmpfile >> $tmpdir/youtube-dl.log 2>&1
