source ~/.vim/plugins.vim  " make sure that plugins are sourced first

set autoread        " reload files when changed on disk
set backspace=2     " fix broken backspace in some setups
set backupcopy=yes  " see :help crontab
set expandtab       " use the appropriate number of spaces for <Tab>
set hlsearch        " highlight search matches
set ignorecase      " case-insensitive search
set incsearch       " search as you type
set laststatus=2    " always show the statusline
set lbr             " break lines between words
set list            " enable rendering of invisible characters
set listchars=tab:▸\ ,eol:¬ " Use symbols for tab and end-of-line
set nojoinspaces    " disable double spaces after periods
set pastetoggle=<F2> " toggle paste mode
set scrolloff=3     " show context above-below cursorline
set shiftwidth=4    " width for autoindents
set smartcase       " case-sensitive search if any caps
set splitright      " new vertical splits on the right side
set tabstop=4       " number of spaces for tab
set textwidth=80    " default line width in number of characters
set wildmenu        " show a navigable menu for tab completion
set wildmode=longest,list,full

" Dictionary word completion using Ctrl-x Ctrl-k
" File from wordlist- (debian) or word- (arch) package
set dictionary+=/usr/share/dict/words

" specify mutt aliases path, autocomplete aliases with @@ in insert mode
let g:mutt_aliases_file = '~/.mutt/aliases'
