#!/bin/bash

file="$1"
line="$2"

[ "${file:0:1}" == "/" ] || file="${PWD}/$file"

exec osascript \
  -e "set ESC to ASCII character 27" \
  -e "tell application \"Vim\" to activate" \
  -e "tell application \"System Events\"" \
  -e "  tell process \"Vim\"" \
  -e "    keystroke ESC & \":set hidden\" & return " \
  -e "    keystroke \":if bufexists('$file')\" & return " \
  -e "    keystroke \":exe \\\":buffer \\\" . bufnr('$file')\"  & return " \
  -e "    keystroke \":else \" & return " \
  -e "    keystroke \":    edit ${file// /\\\\ }\" & return " \
  -e "    keystroke \":endif\" & return " \
  -e "    keystroke \":$line\" & return " \
  -e "    keystroke \"zO\" " \
  -e "  end tell" \
  -e "end tell"
