#!/bin/bash

#
# BSPWM hotkeys
#

# Quit
#super + alt + Escape
super + shift + e
	pamixer --get-volume > ~/.volume \
	pkill panel

# Balance tree
super + b
	bspc desktop -B

# Change windows params
super + {g,f,s,l}
	bspc window -t {floating,fullscreen,sticky,locked}

# Close window
alt + w
	bspc window -c

# Desktops
super + {1-5}
	bspc desktop -f ^{1-5}

# Move focus: super+h,j,k,l
# Swap windows: super+shift+h,j,k,l
super + {_,shift + }{h,j,k,l}
	bspc window --{focus,swap} {left,down,up,right}


# Mouse
~button1
	bspc pointer -g focus

super + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}

super + !button{1-3}
	bspc pointer -t %i %i

super + @button{1-3}
	bspc pointer -u

#
# Non WM hotkeys
#

# URxvt
super + Return
	urxvt -e tmux
super + shift + Return
	urxvt

# XTerm
super + alt + Return
	xterm

# dmenu
super + space
	dmenu_wrapper

# Reload SXHKD
super + r
	pkill -USR1 -x sxhkd \
	~/.config/bspwm/bspwmrc
