#!/bin/bash
#
# Bar Ain't Recursive panel
# by Ivan Sokolov
#

WHITE=f8f8f8
RED=a54242
GREEN=8c9440
BLACK=202020
GRAY=404040

function A {
	echo -n "%{A:$2:}$1%{A}"
}

function B {
	echo -n "%{B#ff$2}$1%{B-}"
}

function F {
	echo -n "%{F#ff$2}$1%{F-}"
}

function o {
	echo "%{+o}$1%{-o}"
}

function u {
	echo "%{+u}$1%{-u}"
}

###

DIV=$(F '|' $GRAY)

###

network() {
	ping -c 1 8.8.8.8 >/dev/null 2>&1 && echo -n $(F + $GREEN) || echo -n $(F - $RED)
}

calendar() {
	#DATE=$(date -u +%d/%m/%y)
	DATE=$(date -u +%Y-%m-%y)
	echo -n $(F $DATE $WHITE)
}

clock() {
	TIME=$(date -u +%H:%M:%S)
	echo -n $(F $TIME $WHITE)
}

volume() {
	#VOLUME=$(pamixer --get-volume)
	VOLUME=$(amixer get Master | grep '\[' | awk '{ print $5; }' | sed 's/\[//' | sed 's/%\]//')
    VCOLOR=$WHITE
	#if [[ $(pamixer --get-mute) -eq 'true' ]]
	#then
	#	VCOLOR=$WHITE
	#else
	#	VCOLOR=$GRAY
	#fi
	#echo -n "$(A $(F $VOLUME $VCOLOR) volume)"
	#echo -n "$(A $(F $VOLUME) volume)"
    echo -n "v:$(A $VOLUME)"
}

battery() {
	BATTERY=$(acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g')
	if [[ $BATTERY -gt 20 ]]
	then
		BCOLOR=$WHITE
	else
		BCOLOR=$RED
	fi
	echo -n b:$(F $BATTERY ff$BCOLOR)
}

layout() {
	#echo -n "$(A $(F $(xkb-switch) $WHITE) layout)"
	echo -n "$(cat ~/.kbd-layout)"
}

mpc_status() {
	if [[ -n $(mpc | grep playing) ]]
	then
		echo -n "$(F "$(mpc current -f "[%title%]")" $WHITE) $DIV "
		echo -n "$(F "$(mpc current -f "[%album%]")" $WHITE) $DIV "
		echo -n "$(F "$(mpc current -f "[%artist%]")" $WHITE) "
	else
		echo -n ''
	fi
}

#		echo -n "$(F "$(mpc current -f "[%title% $(F - $GRAY) %album% $(F - $GRAY) %artist%]|[%file%]")" $WHITE)"

mpc_controls() {
	echo -n ''
}

while true
do
	# Left
	printf '%s' '%{l}'
	# Desktops
	for i in 1 2 3 4 5
	do
		printf ' %s' "%{A:$i:}$(F \| $GRAY)$(F $i $WHITE)$(F \| $GRAY)%{A}"
	done
	
	# Center
	printf '%s' '%{c}'
	printf '%s' "$(mpc_status)"
	# printf '%s' "$(mpc_controls)"
	
	# Right
	printf '%s' '%{r}'
	printf ' %s' $(network) $DIV 
	printf ' %s' $(layout) $DIV
	printf ' %s' $(volume) $DIV 
	printf ' %s' $(battery) $DIV 
	printf ' %s' $(clock)
	printf ' %s \n' $(calendar)

	sleep 0.5s
done | bar \ #bar-aint-recursive \
	-F \#ff$WHITE \
	-B \#ff$BLACK \
	-g 1346x20+10+10 \
    | ~/.config/bspwm/spawner
	#-f '-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-u' \
