#!/bin/bash

# See more in `man bspwm` or on
# https://wiki.archlinux.org/index.php/Bspwm


FIRST_DESK_MAIN=i
REMAINING_DESKS_MAIN="ii iii iv"
FIRST_DESK_SECONDARY=v
REMAINING_DESKS_SECONDARY="vi vii viii"

#MONITORS_ASSOCIATED=`bspc query -M | wc -l` 
#if [[ -z `xrandr | grep " connected" | grep 'VGA\|DP-1'` ]]; then
HOSTNAME=`hostname`
if [[ "$HOSTNAME" == 'iddqd' ]]; then
    bspc desktop ^1 -n $FIRST_DESK_SECONDARY
    bspc config -m ^1 top_padding 14
    bspc monitor -a $REMAINING_DESKS_SECONDARY

    bspc monitor -f next

    bspc desktop Desktop2 -n $FIRST_DESK_MAIN
    bspc monitor -a $REMAINING_DESKS_MAIN
    bspc config -m ^2 top_padding 14
else
    bspc desktop ^1 -n $FIRST_DESK_MAIN
    bspc monitor -a $REMAINING_DESKS_MAIN
    bspc config top_padding 14
fi

# Visual options
bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#605655"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05
bspc config rule_command "$(which rule_command)"

# Placement rules
#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Move focus to the primary monitor
bspc monitor -f primary

/home/adc/.config/bspwm/panel/panel &
